DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
CREATE TABLE AUTHOR(ID IDENTITY PRIMARY KEY, FULLNAME VARCHAR(255));
CREATE TABLE GENRE(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOK(
ID IDENTITY PRIMARY KEY NOT NULL,
TITLE VARCHAR(255) NOT NULL,
IDAUTHOR INT,
FOREIGN KEY (IDAUTHOR) REFERENCES AUTHOR(ID),
IDGENRE INT,
FOREIGN KEY (IDGENRE) REFERENCES GENRE(ID)
);